[package]
name = "hpccg-rs-direct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[build]
rustflags = ["-C", "symbol-mangling-version=v0"]

[dependencies]
libc = "0.2.149"
